### ISSUE TITLE
Allow customization of QR code page

### ISSUE THREAD

**Issue by esune** [openwallet-foundation/acapy-vc-authn-oidc#713]
In order to support custom UX for the QR code page, it needs to be possible to replace the default page and assets.

There are two options to do this:
* (Preferred) Adding a volume with the appropriate resources (HTML, CSS, JS) to the container and having a configuration parameter tell the app where to find the resource files.
* Allow for resources to be replaced in the container with a custom (downstream) build step, ensuring that the expected resources are available in the target directory.

Custom resources for the QR page should always include an HTML page, with CSS and JS resources either defined inline or referenced. This should allow support for more complex SPAs that can be built separately and then injected into the deployment.

**Comment by esune** [comment]
@Gavinok one note worth mentioning (thanks @loneil for reminding me): the QR page is served via a get endpoint as it needs to be processed by the server using a Jinja template to inject the values relevant for the transaction (namely the URL that the QR code will link to). We need to ensure this step is retained so that all variables exposed by the vc-authn service can be referenced and correctly resolved when rendering a template, even if it is a custom one.

**Comment by Gavinok** [comment]
Here are some general plans for this ticket


We want to make the directory and template file into env vars and use a helm volume replacing the [templates](file:///home/gavinok/code/work/vc-authn-oidc/oidc-controller/api/templates) directory for user defined static element.

[Location that needs to be made into a env var](file:///home/gavinok/code/work/vc-authn-oidc/oidc-controller/api/main.py) <https://github.com/bcgov/vc-authn-oidc/blob/main/oidc-controller/api/main.py#L51>

[How we currently import user_variable_substitution.py here](file:///home/gavinok/code/work/vc-authn-oidc/charts/vc-authn-oidc/templates/configmap.yaml) <https://github.com/bcgov/vc-authn-oidc/blob/main/charts/vc-authn-oidc/templates/configmap.yaml#L9>

Make the directory configurable here <https://github.com/bcgov/vc-authn-oidc/blob/main/charts/vc-authn-oidc/values.yaml>

[Add a new volume here](file:///home/gavinok/code/work/vc-authn-oidc/charts/vc-authn-oidc/templates/deployment.yaml) <https://github.com/bcgov/vc-authn-oidc/blob/main/charts/vc-authn-oidc/templates/deployment.yaml#L39>

[The mount this new volume here](file:///home/gavinok/code/work/vc-authn-oidc/charts/vc-authn-oidc/templates/deployment.yaml) <https://github.com/bcgov/vc-authn-oidc/blob/main/charts/vc-authn-oidc/templates/deployment.yaml#L132>

```yaml
volumes:
  - name: jwt-token
    secret:
      secretName: {{ include "vc-authn-oidc.token.secretName" . }}
      defaultMode: 256
  - name: controller-config
    configMap:
      name: {{ include "global.fullname" . }}-controller-config
  - name: template
    emptyDir: {}
```

```yaml
containers:
  - name: {{ include "global.fullname" . }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    volumeMounts:
      - name: template
        mountPath: /path/to/template
```

As far as the handling of passing values into templates a formal api will be outlined on the exposed variables

Users will be responsible for making use of these exposed variables in their templates.
